spring.application.name=demography-service

server.port=58124
http.redirect.port=58081

server.ssl.enabled=true
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-password=demography12345
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=demography-service
server.ssl.enabled-protocols=TLSv1.2,TLSv1.3

person-service.url=https://localhost:58123

spring.mvc.format.date-time=yyyy-MM-dd HH:mm:ss

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

logging.level.org.springframework.web.servlet.resource.ResourceHttpRequestHandler=ERROR
logging.level.org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver=ERROR

spring.web.resources.add-mappings=false
curl -X 'GET' 'https://localhost:58124/demography/nationality/SPAIN/eye-color/GREEN' -H 'accept: application/json'